### ISSUE TITLE
Issue while Self hosting in K8s

### ISSUE THREAD

**Issue by hellodhana** [hoppscotch/helm-charts#18]
I have deployed hoppscotch/hoppscotch:latest image in K8s with config map and secret store. Pod is running fine, but when I query base URL below, the page is blank.

https://amer.ingress.bcs.avnet.com/hoppscotch

Reason the page is blank is that its trying to load asset with without hoppscotch in URL. /hoppscotch is my prefix in ingress controller.

for example:
https://amer.ingress.com/assets/inter-cyrillic-ext-wght-normal-B2xhLi22.woff2
https://amer.ingress.com/assets/index-BLWbyyT9.js

Below is my config.

  VITE_BASE_URL: "http://amer.ingress.com/hoppscotch"
  VITE_SHORTCODE_BASE_URL: "http://amer.ingress.com/hoppscotch"
  VITE_ADMIN_URL: "http://amer.ingress.com/hoppscotch/admin"
  VITE_BACKEND_GQL_URL: "http://amer.ingress.com/hoppscotch/backend/graphql"
  VITE_BACKEND_WS_URL: "wss://amer.ingress.com/hoppscotch/backend/graphql"
  VITE_BACKEND_API_URL: "http://amer.ingress.com/hoppscotch/backend/v1"

Is there any config that I need to set so that it tries to load asset with right URL
https://amer.ingress.com/hoppscotch/assets/inter-cyrillic-ext-wght-normal-B2xhLi22.woff2
https://amer.ingress.com/hoppscotch/assets/index-BLWbyyT9.js

**Comment by liyasthomas** [comment]
@g3Bg2 can you look into this?

**Comment by hellodhana** [comment]
Here is my ingress yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch-ingress
  namespace: hoppscotch
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - amer.ingress.com
    secretName: aks-ingress-tls  
  rules:
    - host: amer.ingress.com
      http:
        paths:
          - path: /hoppscotch(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-service
                port:
                  number: 80

**Comment by hellodhana** [comment]
I am running this in AKS(Azure K8s Service). Not using helm charts. I have many applications running in this cluster and each have a dedicated path in ingress config(example /appl1(/|$)(.*) and /appl2(/|$)(.*)

**Comment by hellodhana** [comment]
I will try this out and comeback if I face issue. Thanks for timely help on this.

**Comment by hellodhana** [comment]
I tried using helm charts but facing same issue.

    ```
urls:
      base: "http://amer.ingress.com/hoppscotch2"
      shortcode: "http://amer.ingress.com/hoppscotch2"
      admin: "http://amer.ingress.com/hoppscotch2/admin"
      backend:
        gql: "http://amer.ingress.com/hoppscotch2/graphql"
        ws: "ws://amer.ingress.com/hoppscotch2/graphql"
        api: "http://amer.ingress.com/hoppscotch2/backend/v1"
      redirect: "http://amer.ingress.com/hoppscotch2"
      whitelistedOrigins: "http://amer.ingress.com/hoppscotch2,http://amer.ingress.com/hoppscotch2/admin,http://amer.ingress.com/hoppscotch2/admin"
```

I am using sub path

```
    community:
      enableSubpathBasedAccess: true
```
