### ISSUE TITLE
[feature]: Add extra env support for deployment and migration job

### ISSUE THREAD

**Issue by jonathanfoster** [hoppscotch/helm-charts#29]
### Summary

Containers should support providing extra environment variables for use cases like injecting HTTP proxy settings. This is particularly useful for running Hoppscotch in enterprise environments which typically lock down HTTP egress and require all requests go through an HTTP proxy. This would also address issue https://github.com/hoppscotch/helm-charts/issues/9.

```yaml
community:
  extraEnvs:
    - name: HTTP_PROXY
      value: http://example.com:8080
    - name: HTTPS_PROXY
      value: http://example.com:8080
    - name: NO_PROXY
      value: http://example.com    
  migration:
    extraEnvs:
      - name: HTTP_PROXY
        value: http://example.com:8080
      - name: HTTPS_PROXY
        value: http://example.com:8080
      - name: NO_PROXY
        value: http://example.com
```

### Why should this be worked on?

Currently, the database migration job fails when HTTP egress is blocked because it must pull packages from NPM. Helm post render hooks aren't an option as they don't support Helm hook resources.

The current setup also limits the ability to override existing settings or inject values from secrets.
