### ISSUE TITLE
Ingress created from the helm chart is having issues with non-nginx ingress controllers

### ISSUE THREAD

**Issue by l-maciej** [hoppscotch/helm-charts#7]
Hey ! 

I've installed application using  community helmchart version 0.1.0.
Issue is when you set spec:.ingressClassName: traefik via values.yaml it still keeps `kubernetes.io/ingress.class: nginx`  and it will be there all the times since it seems to be hard coded in [annotations](https://github.com/hoppscotch/helm-charts/blob/main/charts/she/templates/ingress.yaml#L19). 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  labels:
    app.kubernetes.io/instance: hoppscotch
  name: hoppscotch-community
  namespace: workloads
spec:
  ingressClassName: traefik
```
